# interval constants
DEFAULT_INTERVAL = 3
INTERVAL_START = DEFAULT_INTERVAL
INTERVAL_RESET = DEFAULT_INTERVAL
DATABASE_INTERVAL = DEFAULT_INTERVAL

DATABASE_URL = 'postgresql://vocabulary_owner:npg_vy9zsDc1rAlN@ep-royal-darkness-a9wn62i7-pooler.gwc.azure.neon.tech/vocabulary?sslmode=require'

DEFAULT_SOURCE_LANGUAGE = 'German'
DEFAULT_TARGET_LANGUAGE = 'Korean'


# status codes

STATUS_DEFAULT = 0

STATUS_COLLECTION_DEFAULT = STATUS_DEFAULT
STATUS_PAIR_DEFAULT = STATUS_DEFAULT
STATUS_DELETED = 99